params [
    ["_name", worldName, [""]]
];

//Vehicles status
private _array_veh = [];
{
    private _data = [];
    _data pushBack (typeOf _x);
    _data pushBack (getPosASL _x);
    _data pushBack (getDir _x);
    _data pushBack (fuel _x);
    _data pushBack (getAllHitPointsDamage _x);
    private _cargo = [];
    {
        _cargo pushBack (if (_x isEqualType "") then {
            [_x, "", [[], [], []]]
        } else {
            [typeOf _x, _x getVariable ["ace_rearm_magazineClass", ""], [getWeaponCargo _x, getMagazineCargo _x, getItemCargo _x], _x in btc_chem_contaminated]
        });
    } forEach (_x getVariable ["ace_cargo_loaded", []]);
    _data pushBack _cargo;
    private _cont = [getWeaponCargo _x, getMagazineCargo _x, getItemCargo _x];
    _data pushBack _cont;
    _data append ([_x] call btc_fnc_getVehProperties);
	_data pushBack (vehicleVarName _x);
    _array_veh pushBack _data;
    if (btc_debug_log) then {
        [format ["VEH %1 DATA %2", _x, _data], __FILE__, [false]] call btc_fnc_debug_message;
    };
} forEach (btc_vehicles - [objNull]);

uiSleep 4;

if ((count _array_veh) < 10) then {
	"Problème de sauvegarde des véhicules. Véhicules Réinitialisés" remoteExec ["hint", 0];

	private _array_veh = [ 
		["rhsusf_m113d_usarmy_medical",[13750.2,836.109,9.35366],20.9062,1,[["hithull","hitengine","hitltrack","hitrtrack","hitfuel","hit_turret_glass_l","hit_turret_glass_r","hitslat_left_1","hitslat_left_2","hitslat_left_3","hitslat_right_1","hitslat_right_2","hitslat_right_3","hitslat_back","hitslat_front","hitturret","hitgun","#l svetlo","#p svetlo","#cabin_light","#cargo_light_1"],["telo","motor","pas_l","pas_p","palivo","","","","","","","","","","","vez","zbran","l svetlo","p svetlo","",""],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Track","",[[],[],[]]]],[[["FirstAidKit"],[5]],[[],[]],[[],[]]],[["Desert",1],["IFF_Panels_Hide",0,"hatchGunner",0]],true,false,[0,[]],[],false,[false,-1],"btc_veh_1"],
		["rhsusf_m998_d_4dr_fulltop",[13755.6,962.404,9.34251],358.75,1,[["hitwindshield_1","hitwindshield_2","hitglass1","hitglass2","hitglass3","hitglass4","hitglass5","hitglass6","hitbody","hitfuel","hitlfwheel","hitrfwheel","hitlf2wheel","hitrf2wheel","hitengine","hithull","hitlbwheel","hitlmwheel","hitrbwheel","hitrmwheel","hitrglass","hitlglass","#light_hd_1","#light_hd_2","#light_hd_1","#light_hd_2","#light_hd_1","#light_hd_2","#light_hd_2","#light_hd_1"],["windshield_1","windshield_2","glass1","glass2","glass3","glass4","glass5","glass6","vehicle","fuel","wheel_1","wheel_2","wheel_3","wheel_4","engine","","","","","","","","light_hd_1","light_hd_2","light_hd_1","light_hd_2","light_hd_1","light_hd_2","light_hd_2","light_hd_1"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Wheel","",[[],[],[]]]],[[["arifle_MX_F","FirstAidKit"],[2,10]],[["30Rnd_65x39_caseless_mag","100Rnd_65x39_caseless_mag","HandGrenade","1Rnd_HE_Grenade_shell","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","16Rnd_9x21_Mag","SmokeShell","SmokeShellGreen","SmokeShellOrange","SmokeShellBlue"],[16,6,10,10,4,4,4,4,12,4,4,4,4]],[[],[]]],[["Desert",1],["hide_snorkel",1,"hide_CIP",0,"hide_BFT",0,"hide_Antenna",0,"hide_A2_Parts",0,"Hide_A2Bumper",0,"Hide_Brushguard",1]],false,false,[0,[]],[],false,[false,-1],"btc_veh_2"],
		["rhsusf_m1240a1_usarmy_d",[13766.1,963.29,9.34426],358.437,1,[["hithull","hitfuel","hitengine","hitduke1","hitlfwheel","hitlf2wheel","hitrfwheel","hitrf2wheel","hitglass1","hitglass2","hitglass3","hitglass4","hitglass5","hitglass6","hitbody","hitlbwheel","hitlmwheel","hitrbwheel","hitrmwheel","hitrglass","hitlglass","#light_l","#light_l","#light_r","#light_r","#light_l","#light_r","#light_r","#light_l"],["karoserie","palivo","motor","duke1","wheel_1_1_steering","wheel_1_2_steering","wheel_2_1_steering","wheel_2_2_steering","glass1","glass2","glass3","glass4","glass5","glass6","karoserie","","","","","","","light_l","light_l","light_r","light_r","light_l","light_r","light_r","light_l"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Wheel","",[[],[],[]]]],[[["arifle_MX_F","FirstAidKit"],[2,10]],[["30Rnd_65x39_caseless_mag","100Rnd_65x39_caseless_mag","HandGrenade","1Rnd_HE_Grenade_shell","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","16Rnd_9x21_Mag","SmokeShell","SmokeShellGreen","SmokeShellOrange","SmokeShellBlue"],[16,6,10,10,4,4,4,4,12,4,4,4,4]],[[],[]]],[[],["DoorLF",0,"DoorRF",0,"DoorLB",0,"DoorRB",0,"DUKE_Hide",0,"hide_spare",0]],false,false,[0,[]],[],false,[false,-1],"btc_veh_3"],
		["rhsusf_m1a1aimd_usarmy",[13755.2,1000.29,9.3431],88.4085,1,[["armor_composite_40","armor_composite_50","armor_composite_60","armor_composite_80","armor_composite_85","hitfueltank_left","hitfueltank_right","hitfuel","hitammohull","hitammo","hithull","hitengine","hitltrack","hitrtrack","hit_optic_driver","hit_optic_dvea","hit_optic_driver_rear","hitturret","hitgun","hit_gps_headmirror","hit_gps_optical","hit_gps_tis","hit_optic_gps","hit_optic_gps_ti","hitturretcom","hitguncom","hit_optic_comperiscope","hit_optic_comm2","hit_optic_comcwss","hit_optic_loaderperiscope","hit_optic_loaderperiscope","#light_l","#light_l","#light_r","#light_r"],["","","","","","hit_fueltank_left","hit_fueltank_right","hit_fuel","","hit_ammo","hit_hull","hit_engine","hit_trackl","hit_trackr","","","","vez","zbran","","","","","","","","","","","","","light_l","light_l","light_r","light_r"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Track","",[[],[],[]]]],[[["arifle_MXC_F","FirstAidKit"],[2,10]],[["SmokeShell","SmokeShellBlue","30Rnd_65x39_caseless_mag"],[2,2,4]],[[],[]]],[["desert",1],["IFF_Panels_Hide",0,"Miles_Hide",0]],false,false,[0,[]],[],false,[false,-1],"btc_veh_4"],
		["rhsusf_m113d_usarmy",[13875.3,885.683,9.35309],271.112,1,[["hithull","hitengine","hitltrack","hitrtrack","hitfuel","hit_turret_glass_l","hit_turret_glass_r","hitslat_left_1","hitslat_left_2","hitslat_left_3","hitslat_right_1","hitslat_right_2","hitslat_right_3","hitslat_back","hitslat_front","hitturret","hitgun","hitturret","hitgun","#l svetlo","#p svetlo","#cabin_light","#cargo_light_1","#cabin_light","#cargo_light_1"],["telo","motor","pas_l","pas_p","palivo","","","","","","","","","","","vez","zbran","vez","zbran","l svetlo","p svetlo","","","",""],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Track","",[[],[],[]]]],[[["FirstAidKit"],[5]],[[],[]],[[],[]]],[["Desert",1],["IFF_Panels_Hide",0,"hatchGunner",0,"Hide_Turret_Armor_Front",0,"Hide_Turret_Armor_Side",0]],false,false,[0,[]],[],false,[false,-1],"btc_veh_5"],
		["rhsusf_m1025_d_m2",[13750,962.219,9.33982],357.706,1,[["hitwindshield_1","hitwindshield_2","hitglass1","hitglass2","hitglass3","hitglass4","hitglass5","hitglass6","hitbody","hitfuel","hitlfwheel","hitrfwheel","hitlf2wheel","hitrf2wheel","hitengine","hithull","hitlbwheel","hitlmwheel","hitrbwheel","hitrmwheel","hitrglass","hitlglass","hitturret","hitgun","#light_hd_1","#light_hd_2","#light_hd_1","#light_hd_2","#light_hd_1","#light_hd_2","#light_hd_2","#light_hd_1"],["windshield_1","windshield_2","glass1","glass2","glass3","glass4","","","vehicle","fuel","wheel_1","wheel_2","wheel_3","wheel_4","engine","","","","","","","","","","light_hd_1","light_hd_2","light_hd_1","light_hd_2","light_hd_1","light_hd_2","light_hd_2","light_hd_1"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Wheel","",[[],[],[]]]],[[["arifle_MX_F","FirstAidKit"],[2,10]],[["30Rnd_65x39_caseless_mag","100Rnd_65x39_caseless_mag","HandGrenade","1Rnd_HE_Grenade_shell","1Rnd_Smoke_Grenade_shell","1Rnd_SmokeGreen_Grenade_shell","1Rnd_SmokeOrange_Grenade_shell","1Rnd_SmokeBlue_Grenade_shell","16Rnd_9x21_Mag","SmokeShell","SmokeShellGreen","SmokeShellOrange","SmokeShellBlue"],[16,6,10,10,4,4,4,4,12,4,4,4,4]],[[],[]]],[["Desert",1],["hide_snorkel",1,"hide_CIP",0,"hide_BFT",0,"hide_Antenna",0,"hide_A2_Parts",0,"Hide_A2Bumper",0,"Hide_Brushguard",1]],false,false,[0,[]],[],false,[false,-1],"btc_veh_6"],
		["rhsusf_m1a2sep1d_usarmy",[13755.2,1008,9.34293],88.3004,1,[["armor_composite_40","armor_composite_50","armor_composite_60","armor_composite_80","armor_composite_85","hitfueltank_left","hitfueltank_right","hitfuel","hitammohull","hitammo","hithull","hitengine","hitltrack","hitrtrack","hit_optic_driver","hit_optic_dvea","hit_optic_driver_rear","hitturret","hitgun","hit_gps_headmirror","hit_gps_optical","hit_gps_tis","hit_optic_gps","hit_optic_gps_ti","hitturretcom","hitguncom","hit_optic_citv","hit_optic_loaderperiscope","hitturretcomm2","hitguncomm2","hitturretloader","hitgunloader","#light_l","#light_l","#light_r","#light_r"],["","","","","","hit_fueltank_left","hit_fueltank_right","hit_fuel","","hit_ammo","hit_hull","hit_engine","hit_trackl","hit_trackr","","","","vez","zbran","","","","","","","","","","","","","","light_l","light_l","light_r","light_r"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Track","",[[],[],[]]]],[[["arifle_MXC_F","FirstAidKit"],[2,10]],[["SmokeShell","SmokeShellBlue","30Rnd_65x39_caseless_mag"],[2,2,4]],[[],[]]],[["desert",1],["IFF_Panels_Hide",0,"Miles_Hide",0]],false,false,[0,[]],[],false,[false,-1],"btc_veh_7"],
		["rhsusf_M1078A1P2_D_fmtv_usarmy",[13814.3,954.943,9.33347],272.163,1,[["hitfuel","hitengine","hitbody","hitlfwheel","hitlf2wheel","hitlmwheel","hitlbwheel","hitrfwheel","hitrf2wheel","hitrmwheel","hitrbwheel","hitglass1","hitglass2","hitglass3","hitglass4","hithull","hitrglass","hitlglass","hitglass5","hitglass6","#light_l","#light_l","#light_r","#light_r","#light_l","#light_r","#light_r","#light_l","#cabin_light1"],["palivo","motor","","wheel_1_1_steering","wheel_1_2_steering","","","wheel_2_1_steering","wheel_2_2_steering","","","glass1","glass2","glass3","glass4","palivo","","","glass5","","light_l","light_l","light_r","light_r","light_l","light_r","light_r","light_l",""],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Wheel","",[[],[],[]]]],[[["FirstAidKit"],[10]],[[],[]],[[],[]]],[["rhs_desert",1],["hide_cover",0,"hide_spare",0,"hide_scaffold",0,"hide_bench",0]],false,false,[0,[]],[],false,[false,-1],"btc_veh_8"],
		["RHS_AH64D",[13457.1,825.072,9.33967],178.93,0.999929,[["hithull","hitfuel","hitavionics","hitengine1","hitengine2","hitengine","hithrotor","hittail","hitvrotor","hitglass1","hitglass2","hitglass3","hitglass4","hitglass5","hitglass6","hit_longbow","hit_optic_tads","hit_optic_pnvs","hithydraulics","hittransmission","hithstabilizerl1","hithstabilizerr1","hitvstabilizer1","hitpylon1","hitpylon2","hitpylon3","hitpylon4","hitpylon5","hitpylon6","hitmissiles","hitglass7","hitglass8","hitwinch","hitrglass","hitlglass","hitengine3","hitlight","hitgear","hitpitottube","hitstaticport","hitstarter1","hitstarter2","hitstarter3","hitturret","hitgun","#l svetlo"],["hull_hit","fuel_hit","elektronika","hit_engine_1","hit_engine_2","engine_hit","velka vrtule","hit_tail","mala vrtule","glass1","glass2","glass3","glass4","glass5","","","","","hit_hydraulics","hit_transmission","hit_stabilizer_l","hit_stabilizer_r","","hit_pylon_1","hit_pylon_2","hit_pylon_3","hit_pylon_4","hit_pylon_5","hit_pylon_6","","","","","","","","","","","","","","","","","l svetlo"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[],[[["rhs_weap_m4_carryhandle","FirstAidKit"],[2,4]],[["rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_m18_green","rhs_mag_m18_yellow","rhs_mag_m18_red","rhs_mag_m18_purple","rhs_mag_an_m8hc"],[8,2,2,2,2,2]],[["rhsusf_ihadss","amp_slingload_CargoSling"],[2,4]]],[["standard",1],["radar_hide",0]],false,false,[0,[]],["","rhs_mag_M151_19","rhs_mag_AGM114L_4","rhs_mag_AGM114K_4","rhs_mag_M151_19","","rhsusf_M130_CMFlare_Chaff_Magazine_x2"],false,[false,-1],"btc_veh_10"],
		["B_Truck_01_ammo_F",[13792.3,836.909,9.36791],180.835,1,[["hitfuel","hitengine","hitbody","hitlfwheel","hitlf2wheel","hitlmwheel","hitlbwheel","hitrfwheel","hitrf2wheel","hitrmwheel","hitrbwheel","hitglass1","hitglass2","hitglass3","hitglass4","hithull","hitrglass","hitlglass","hitglass5","hitglass6","#light_l","#light_r","#light_l","#light_r"],["palivo","motor","karoserie","wheel_1_1_steering","wheel_1_2_steering","wheel_1_3_steering","wheel_1_4_steering","wheel_2_1_steering","wheel_2_2_steering","wheel_2_3_steering","wheel_2_4_steering","glass1","glass2","glass3","glass4","palivo","","","","","light_l","light_r","light_l","light_r"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Wheel","",[[],[],[]]]],[[["FirstAidKit"],[10]],[[],[]],[[],[]]],[[],[]],false,false,[0,[]],[],false,[true,-1],"btc_veh_11"],
		["B_Truck_01_fuel_F",[13800.8,836.798,9.3695],181.625,1,[["hitfuel","hitengine","hitbody","hitlfwheel","hitlf2wheel","hitlmwheel","hitlbwheel","hitrfwheel","hitrf2wheel","hitrmwheel","hitrbwheel","hitglass1","hitglass2","hitglass3","hitglass4","hithull","hitrglass","hitlglass","hitglass5","hitglass6","#light_l","#light_r","#light_l","#light_r"],["palivo","motor","karoserie","wheel_1_1_steering","wheel_1_2_steering","wheel_1_3_steering","wheel_1_4_steering","wheel_2_1_steering","wheel_2_2_steering","wheel_2_3_steering","wheel_2_4_steering","glass1","glass2","glass3","glass4","palivo","","","","","light_l","light_r","light_l","light_r"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Wheel","",[[],[],[]]]],[[["FirstAidKit"],[10]],[[],[]],[[],[]]],[[],[]],false,false,[10000,[]],[],false,[false,-1],"btc_veh_12"],
		["B_Truck_01_Repair_F",[13746.5,937.035,9.35485],179.699,1,[["hitfuel","hitengine","hitbody","hitlfwheel","hitlf2wheel","hitlmwheel","hitlbwheel","hitrfwheel","hitrf2wheel","hitrmwheel","hitrbwheel","hitglass1","hitglass2","hitglass3","hitglass4","hithull","hitrglass","hitlglass","hitglass5","hitglass6","#light_l","#light_r","#light_l","#light_r"],["palivo","motor","karoserie","wheel_1_1_steering","wheel_1_2_steering","wheel_1_3_steering","wheel_1_4_steering","wheel_2_1_steering","wheel_2_2_steering","wheel_2_3_steering","wheel_2_4_steering","glass1","glass2","glass3","glass4","palivo","","","","","light_l","light_r","light_l","light_r"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Wheel","",[[],[],[]]]],[[["FirstAidKit"],[10]],[[],[]],[[],[]]],[[],[]],false,true,[0,[]],[],false,[false,-1],"btc_veh_13"],
		["rhsusf_CH53E_USMC_D",[13692.1,822.843,9.38581],177.618,0.999989,[["hithull","hitengine1","hitengine2","hitengine","hitfuel","hitfuel2","hitavionics","hittail","hitvrotor","hithrotor","hitglass1","hitglass2","hitglass3","hitglass4","hitglass5","hitglass6","hitglass7","hitglass8","hitglass9","hitglass10","hitglass11","hitglass12","hitglass13","hitglass14","hitglass15","hitglass16","hitglass17","hitmissiles","hitrglass","hitlglass","hitengine3","hitwinch","hittransmission","hitlight","hithydraulics","hitgear","hithstabilizerl1","hithstabilizerr1","hitvstabilizer1","hitpitottube","hitstaticport","hitstarter1","hitstarter2","hitstarter3","hitturret","hitgun","#landleft","#landright","#cabin_light","#cargo_light_1","#cargo_light_2","#cargo_light_3"],["","","","","hit_fuel_1","hit_fuel_2","elektronika","","mala vrtule","velka vrtule","glass1","glass2","glass3","glass4","glass5","glass6","glass7","glass8","glass9","glass10","glass11","glass12","glass13","glass14","glass15","glass16","glass17","","","","","","","","","","","","","","","","","","","","landleft","landright","","","",""],[0,0,0,0,0,0,0.0292076,0,0,0,0.0421612,0.0310618,0.0281474,0.0251809,0.0880319,0.0576022,0.0524516,0.0365227,0.0897312,0.477524,0.477524,0.477524,0.103554,0.477524,0.477524,0.477524,0.280211,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0141821,0.0136736,0,0,0,0]],[],[[["FirstAidKit","Medikit"],[8,1]],[["SmokeShell","SmokeShellBlue"],[2,2]],[["amp_slingload_CargoSling"],[4]]],[["standard",1],["hide_winch",0,"hide_ANAAQ24",0,"mainRotor_folded_handler",0,"hide_cargo",0]],false,false,[0,[]],["rhsusf_ANALE39_CMFlare_Chaff_Magazine_x2"],false,[false,-1],"btc_veh_14"],
		["rhsusf_M1083A1P2_B_D_fmtv_usarmy",[13813.3,922.28,9.33194],269.533,1,[["hitfuel","hitengine","hitbody","hitlfwheel","hitlf2wheel","hitlmwheel","hitlbwheel","hitrfwheel","hitrf2wheel","hitrmwheel","hitrbwheel","hitglass1","hitglass2","hitglass3","hitglass4","hithull","hitrglass","hitlglass","hitglass5","hitglass6","#light_l","#light_l","#light_r","#light_r","#light_l","#light_r","#light_r","#light_l","#cabin_light1"],["palivo","motor","","wheel_1_1_steering","wheel_1_2_steering","wheel_1_3_steering","","wheel_2_1_steering","wheel_2_2_steering","wheel_2_3_steering","","glass1","glass2","glass3","glass4","palivo","","","glass5","","light_l","light_l","light_r","light_r","light_l","light_r","light_r","light_l",""],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Wheel","",[[],[],[]]]],[[["FirstAidKit"],[10]],[[],[]],[[],[]]],[["rhs_desert",1],["hide_cover",0,"hide_spare",0,"hide_scaffold",0,"hide_bench",0]],false,false,[0,[]],[],false,[false,-1],"btc_veh_15"],
		["rhsusf_M1083A1P2_D_flatbed_fmtv_usarmy",[13814.1,938.661,9.33426],271.119,1,[["hitfuel","hitengine","hitbody","hitlfwheel","hitlf2wheel","hitlmwheel","hitlbwheel","hitrfwheel","hitrf2wheel","hitrmwheel","hitrbwheel","hitglass1","hitglass2","hitglass3","hitglass4","hithull","hitrglass","hitlglass","hitglass5","hitglass6","#light_l","#light_l","#light_r","#light_r","#light_l","#light_r","#light_r","#light_l","#cabin_light1"],["palivo","motor","","wheel_1_1_steering","wheel_1_2_steering","wheel_1_3_steering","","wheel_2_1_steering","wheel_2_2_steering","wheel_2_3_steering","","glass1","glass2","glass3","glass4","palivo","","","glass5","","light_l","light_l","light_r","light_r","light_l","light_r","light_r","light_l",""],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Wheel","",[[],[],[]]]],[[["FirstAidKit"],[10]],[[],[]],[[],[]]],[["rhs_desert",1],["hide_cover",1,"hide_scaffold",1,"hide_bench",1,"hide_spare",0]],false,false,[0,[]],[],false,[false,-1],"btc_veh_16"],
		["B_Truck_01_ammo_F",[13802.4,686.766,9.36722],334.781,1,[["hitfuel","hitengine","hitbody","hitlfwheel","hitlf2wheel","hitlmwheel","hitlbwheel","hitrfwheel","hitrf2wheel","hitrmwheel","hitrbwheel","hitglass1","hitglass2","hitglass3","hitglass4","hithull","hitrglass","hitlglass","hitglass5","hitglass6","#light_l","#light_r","#light_l","#light_r"],["palivo","motor","karoserie","wheel_1_1_steering","wheel_1_2_steering","wheel_1_3_steering","wheel_1_4_steering","wheel_2_1_steering","wheel_2_2_steering","wheel_2_3_steering","wheel_2_4_steering","glass1","glass2","glass3","glass4","palivo","","","","","light_l","light_r","light_l","light_r"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Wheel","",[[],[],[]]]],[[["FirstAidKit"],[10]],[[],[]],[[],[]]],[[],[]],false,false,[0,[]],[],false,[true,-1],"btc_veh_17"],
		["B_Truck_01_Repair_F",[13802.8,703.85,9.36723],358.667,1,[["hitfuel","hitengine","hitbody","hitlfwheel","hitlf2wheel","hitlmwheel","hitlbwheel","hitrfwheel","hitrf2wheel","hitrmwheel","hitrbwheel","hitglass1","hitglass2","hitglass3","hitglass4","hithull","hitrglass","hitlglass","hitglass5","hitglass6","#light_l","#light_r","#light_l","#light_r"],["palivo","motor","karoserie","wheel_1_1_steering","wheel_1_2_steering","wheel_1_3_steering","wheel_1_4_steering","wheel_2_1_steering","wheel_2_2_steering","wheel_2_3_steering","wheel_2_4_steering","glass1","glass2","glass3","glass4","palivo","","","","","light_l","light_r","light_l","light_r"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[["ACE_Wheel","",[[],[],[]]]],[[["FirstAidKit"],[10]],[[],[]],[[],[]]],[[],[]],false,true,[0,[]],[],false,[false,-1],"btc_veh_18"],
		["RHS_UH60M_d",[13650.6,821.038,9.42947],180.163,1,[["hithull","hitengine1","hitengine2","hitengine","hittail","hitvrotor","hithrotor","hitwinch","hitglass7","hithydraulics","hittransmission","hithstabilizerl1","hithstabilizerr1","hitpylon1","hitpylon2","hitpylon3","hitpylon4","hitfuel","hitavionics","hitmissiles","hitglass1","hitglass2","hitglass3","hitglass4","hitglass5","hitglass6","hitglass8","hitglass9","hitglass10","hitglass11","hitglass12","hitglass13","hitglass14","hitrglass","hitlglass","hitengine3","hitlight","hitgear","hitvstabilizer1","hitpitottube","hitstaticport","hitstarter1","hitstarter2","hitstarter3","#p svetlo","#l svetlo","#cabin_light","#cargo_light_1","#cargo_light_2"],["hull_hit","engine_1_hit","engine_2_hit","engine_hit","hit_tail","tail_rotor_hit","velka vrtule","hit_winch","glass7","hit_hydraulics","hit_transmission","","","","","","","fuel_hit","avionics_hit","","glass1","glass2","glass3","glass4","glass5","glass6","","","","","","","","","","","","","","","","","","","p svetlo","l svetlo","","",""],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[],[[["FirstAidKit","Medikit"],[8,1]],[["SmokeShell","SmokeShellBlue"],[2,2]],[["amp_slingload_CargoSling"],[4]]],[["standard",1],["doors_hide",1,"Hide_Scopes",0]],false,false,[0,[]],["rhsusf_M130_CMFlare_Chaff_Magazine_x2"],false,[false,-1],"btc_veh_19"],
		["RHS_AH1Z",[13413.4,825.025,9.33859],178.314,1,[["hithull","hitfuel","hitavionics","hitmissiles","hitengine1","hitengine2","hitengine","hithrotor","hittail","hitvrotor","hitglass1","hitglass2","hitglass3","hitglass4","hitglass5","hitglass6","hitpylon1","hitpylon2","hitpylon3","hitpylon4","hitpylon5","hitpylon6","hitglass7","hitglass8","hitwinch","hitrglass","hitlglass","hitengine3","hittransmission","hitlight","hithydraulics","hitgear","hithstabilizerl1","hithstabilizerr1","hitvstabilizer1","hitpitottube","hitstaticport","hitstarter1","hitstarter2","hitstarter3","hitturret","hitgun","#l svetlo"],["","fuel_hit","avionics_hit","","engine_1_hit","engine_2_hit","","velka vrtule","","mala vrtule","glass1","glass2","glass3","glass4","glass5","","hit_pylon_1","hit_pylon_2","hit_pylon_3","hit_pylon_4","hit_pylon_5","hit_pylon_6","","","","","","","","","","","","","","","","","","","","","l svetlo"],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[],[[["rhs_weap_m4_carryhandle","FirstAidKit"],[2,4]],[["rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_m18_green","rhs_mag_m18_yellow","rhs_mag_m18_red","rhs_mag_m18_purple","rhs_mag_an_m8hc"],[8,2,2,2,2,2]],[["amp_slingload_CargoSling"],[4]]],[["standard",1],["mainRotor_folded",0]],false,false,[0,[]],["rhs_mag_Sidewinder_heli_2","rhs_mag_AGM114K_4","rhs_mag_M151_19_green","rhs_mag_M151_19_green","rhs_mag_AGM114K_4","rhs_mag_Sidewinder_heli_2","rhsusf_ANALE39_CMFlare_Chaff_Magazine_x4"],false,[false,-1],"btc_veh_20"],
		["RHS_UH60M_MEV2",[13796.9,880.972,9.42946],268.861,1,[["hithull","hitengine1","hitengine2","hitengine","hittail","hitvrotor","hithrotor","hitwinch","hitglass7","hithydraulics","hittransmission","hithstabilizerl1","hithstabilizerr1","hitpylon1","hitpylon2","hitpylon3","hitpylon4","hitfuel","hitavionics","hitmissiles","hitglass1","hitglass2","hitglass3","hitglass4","hitglass5","hitglass6","hitglass8","hitglass9","hitglass10","hitglass11","hitglass12","hitglass13","hitglass14","hitrglass","hitlglass","hitengine3","hitlight","hitgear","hitvstabilizer1","hitpitottube","hitstaticport","hitstarter1","hitstarter2","hitstarter3","#p svetlo","#l svetlo","#cabin_light","#cargo_light_1","#cargo_light_2"],["hull_hit","engine_1_hit","engine_2_hit","engine_hit","hit_tail","tail_rotor_hit","velka vrtule","hit_winch","glass7","hit_hydraulics","hit_transmission","","","","","","","fuel_hit","avionics_hit","","glass1","glass2","glass3","glass4","glass5","glass6","","","","","","","","","","","","","","","","","","","p svetlo","l svetlo","","",""],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]],[],[[[],[]],[["SmokeShellGreen","ACE_M14","DemoCharge_Remote_Mag"],[10,10,5]],[["ACE_fieldDressing","ACE_elasticBandage","ACE_bloodIV","ACE_bodyBag","ACE_CableTie","ACE_DefusalKit","ACE_epinephrine","ACE_morphine","ACE_packingBandage","ACE_personalAidKit","ACE_plasmaIV","ACE_salineIV","ACE_tourniquet","ACE_surgicalKit","ACE_EarPlugs","MineDetector","ACE_Clacker","adv_aceCPR_AED","amp_slingload_CargoSling"],[40,40,10,4,6,2,20,20,40,4,10,10,10,1,4,1,5,1,4]]],[["standard",1],["Hide_Scopes",0,"doors_hide",0]],true,false,[0,[]],["rhsusf_M130_CMFlare_Chaff_Magazine_x2"],false,[false,-1],"btc_veh_21"]
	];

	profileNamespace setVariable [format ["btc_hm_%1_vehs", worldName], _array_veh];
	saveProfileNamespace;
	
} else {	

	profileNamespace setVariable [format ["btc_hm_%1_vehs", _name], _array_veh];
	saveProfileNamespace;
};



